name: Complete CI

on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest
    name: Backend Tests

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Run tests
        run: ./mvnw -q -DskipTests=false test
        working-directory: ./backend
      
      - name: Build package
        run: ./mvnw -q clean package
        working-directory: ./backend

  frontend:
    runs-on: ubuntu-latest
    name: Frontend Tests

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      
      - name: Run ESLint
        run: npm run lint
        working-directory: ./frontend
      
      - name: Type check
        run: npx tsc --noEmit
        working-directory: ./frontend
      
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend
